baseURL = 'https://ankidoc.tifrueh.ch'
languageCode = 'en-GB'
title = 'ETH-Ankidoc'
theme = 'ankidoc'
pluralizeListTitles = false
capitalizeListTitles = false

[taxonomies]
    tag = 'tags'

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['asciidoctor']

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'server'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
        source-highlighter = 'rouge'
